### PR TITLE
Add ComicExtra and MangaPill

### PR DESCRIPTION
**Pull request by GameFuzzy**
Should work fine but you can all test it just in case

### CODE REVIEW

**Comment by ConradWeiser** [comment]
Are you sure that this source is working to it's full capacity?

I've pulled up [Batman Beyond](https://www.comicextra.com/comic/batman-beyond-2010) both on the website, and on the app.
The app populates the chapters properly, but every time I try to read on Paperback, I get a 'page does not exist' sheet.

However I can verify on the website that the pages for the chapters I'm looking at definitely exist.

**Comment by GameFuzzy** [comment]
I kind of suspected as much tbh. My attempt at filtering out missing pages seems to have filtered too much.

**Comment by ConradWeiser** [comment]
Leave a comment when this PR is ready to be looked at again! - let me know if you need some advice.

**Comment by GameFuzzy** [comment]
Got it

**Comment by GameFuzzy** [comment]
PR should be ready for review again

**Comment by GameFuzzy** [comment]
Decided to merge MangaPill into the master branch since it's done anyway and it would be easier for you to test that way.

**Comment by ConradWeiser** [comment]
ComicExtra looks to be up to spec - The "No Photo" bits are a little strange, but that's just nature of the website, huh? A brief investigation yielded that there's no easy way to synthesize the image URL from the information you have on the page.

**Comment by ConradWeiser** [comment]
MangaPill also looks good!

**Pull request merged**
