### PR TITLE
Update ReadComicsTo.ts

### PR DESCRIPTION
**Pull request by nar1n**

### CODE REVIEW

**Review by ConradWeiser — CHANGES_REQUESTED** [review]
Please increment the version number

**Review by ConradWeiser — APPROVED** [review]
Tested on the application, this works fine

**Review by Aur0raN — APPROVED** [review]
Looks good,
Would require a name change eventually, I'll get to it

**Comment by TheNetsky** [comment]
I'm very proud of you. :)

**Comment by nar1n** [comment]
> Looks good,
> Would require a name change eventually, I'll get to it

Make sure to not change the folder name as that is the identifier

**Pull request merged**
