### PR TITLE
Add info for the homepage

### PR DESCRIPTION
**Pull request by FramboisePi**
RepositoryName: "[PROMISES] Additional Sources"
Description: "Additional sources for Paperback"
The base URL should be deducted from GitHub environment variable.

### CODE REVIEW

**Comment by ConradWeiser** [comment]
Is this set to merge still @FramboisePi ? - The Package-lock file will be the 'master' branch version in the merge.

**Comment by FramboisePi** [comment]
It is. Thanks Vibrant

**Comment by ConradWeiser** [comment]
It seems like you're going to have to resolve the merge conflict yourself - I don't have write access to your fork. 
Once you're all set with that, we can get it moved in.

**Comment by FramboisePi** [comment]
It should be okay, I've added package-lock.json from the master branch.

**Comment by ConradWeiser** [comment]
Closing due to inactivity, this may be my bad for not reviewing it before merge conflicts started to pop up. Feel free to reopen this and I’ll make time to start a dialog and figure out what the state of this is

**Pull request closed without merging**
